# Generated by Django 5.1.4 on 2025-01-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('title2', models.CharField(max_length=122)),
                ('title3', models.CharField(max_length=122)),
                ('title4', models.CharField(max_length=122)),
                ('description', models.CharField(max_length=122)),
                ('description2', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
